name: Actualizar Streamers

on:
  schedule:
    - cron: "*/15 * * * *"

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Llamar API de actualización
        run: |
          curl --fail \
            -H "Authorization: Bearer ${{ secrets.WT_CRON_SECRET_GITHUB }}" \
            https://wt-beryl.vercel.app